### ISSUE TITLE
Add Phoenix temporary assigns

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-chat-example#5]
Use [temporary assigns](https://hexdocs.pm/phoenix_live_view/dom-patching.html#temporary-assigns) when adding a new message to the chat instead of keeping all the messages in memory

**Comment by SimonLab** [comment]
done with #10

**Comment by nelsonic** [comment]
Thanks @SimonLab. 👍🏻
this is a good enhancement.
It’s definitely worth explaining that it’s a “post launch” optimisation. i.e. in the beginning of a project/App, it might actually not be desidratar to do this because having the chat in-memory is a good UX speed-boost. And if you never get to 100+ people using the App it won’t matter because your App won’t run out of memory with low usage. 💭
